[tool.mypy]
python_version = "3.10"
show_error_codes = true
disallow_untyped_calls = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true

warn_unused_configs = true
warn_unused_ignores = true
no_warn_no_return = true

strict_equality = true

[[tool.mypy.overrides]]
module = [
  "wazo_lib_rest_client.*"
]
ignore_missing_imports = true

[tool.black]
skip-string-normalization = true

[tool.flake8]
show-source = true
max-line-length = 99
application-import-names = "wazo_auth_client"
ignore = [
  "E203", # whitespace before ':'
  "W503", # line break before binary operator
]
exclude = [
    ".tox",
    ".eggs",
]

[tool.isort]
profile = "black"
py_version = 39
