debug: True
foreground: True
log_filename: /tmp/xivo-auth.log

rest_api:
  https:
    certificate: /data/ssl/server.crt
    private_key: /data/ssl/server.key

  cors:
    enabled: True
    allow_headers: Content-Type, authorization, x-auth-token

enabled_plugins:
  - mock

amqp:
  uri: amqp://guest:guest@rabbitmq:5672/
  exchange_name: xivo
  exchange_type: topic

consul:
  scheme: https
  host: consul
  port: 8500
  token: 'the_one_ring'
  verify: false

service_discovery:
  enabled: false
